// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic.proto

#ifndef PROTOBUF_basic_2eproto__INCLUDED
#define PROTOBUF_basic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace BasicProtobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_basic_2eproto();
void protobuf_AssignDesc_basic_2eproto();
void protobuf_ShutdownFile_basic_2eproto();

class ConnectionResponse;

enum ConnectionResponse_ResponseCode {
  ConnectionResponse_ResponseCode_OK = 200,
  ConnectionResponse_ResponseCode_BadMessageFormatting = 400,
  ConnectionResponse_ResponseCode_UnknownService = 404,
  ConnectionResponse_ResponseCode_NotSupportedVersion = 405,
  ConnectionResponse_ResponseCode_Timeout = 408,
  ConnectionResponse_ResponseCode_ProtocolError = 410,
  ConnectionResponse_ResponseCode_InternalError = 500,
  ConnectionResponse_ResponseCode_InvalidKey = 429,
  ConnectionResponse_ResponseCode_InvalidRequestParams = 406
};
bool ConnectionResponse_ResponseCode_IsValid(int value);
const ConnectionResponse_ResponseCode ConnectionResponse_ResponseCode_ResponseCode_MIN = ConnectionResponse_ResponseCode_OK;
const ConnectionResponse_ResponseCode ConnectionResponse_ResponseCode_ResponseCode_MAX = ConnectionResponse_ResponseCode_InternalError;
const int ConnectionResponse_ResponseCode_ResponseCode_ARRAYSIZE = ConnectionResponse_ResponseCode_ResponseCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConnectionResponse_ResponseCode_descriptor();
inline const ::std::string& ConnectionResponse_ResponseCode_Name(ConnectionResponse_ResponseCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConnectionResponse_ResponseCode_descriptor(), value);
}
inline bool ConnectionResponse_ResponseCode_Parse(
    const ::std::string& name, ConnectionResponse_ResponseCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConnectionResponse_ResponseCode>(
    ConnectionResponse_ResponseCode_descriptor(), name, value);
}
// ===================================================================

class ConnectionResponse : public ::google::protobuf::Message {
 public:
  ConnectionResponse();
  virtual ~ConnectionResponse();

  ConnectionResponse(const ConnectionResponse& from);

  inline ConnectionResponse& operator=(const ConnectionResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectionResponse& default_instance();

  void Swap(ConnectionResponse* other);

  // implements Message ----------------------------------------------

  ConnectionResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConnectionResponse& from);
  void MergeFrom(const ConnectionResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ConnectionResponse_ResponseCode ResponseCode;
  static const ResponseCode OK = ConnectionResponse_ResponseCode_OK;
  static const ResponseCode BadMessageFormatting = ConnectionResponse_ResponseCode_BadMessageFormatting;
  static const ResponseCode UnknownService = ConnectionResponse_ResponseCode_UnknownService;
  static const ResponseCode NotSupportedVersion = ConnectionResponse_ResponseCode_NotSupportedVersion;
  static const ResponseCode Timeout = ConnectionResponse_ResponseCode_Timeout;
  static const ResponseCode ProtocolError = ConnectionResponse_ResponseCode_ProtocolError;
  static const ResponseCode InternalError = ConnectionResponse_ResponseCode_InternalError;
  static const ResponseCode InvalidKey = ConnectionResponse_ResponseCode_InvalidKey;
  static const ResponseCode InvalidRequestParams = ConnectionResponse_ResponseCode_InvalidRequestParams;
  static inline bool ResponseCode_IsValid(int value) {
    return ConnectionResponse_ResponseCode_IsValid(value);
  }
  static const ResponseCode ResponseCode_MIN =
    ConnectionResponse_ResponseCode_ResponseCode_MIN;
  static const ResponseCode ResponseCode_MAX =
    ConnectionResponse_ResponseCode_ResponseCode_MAX;
  static const int ResponseCode_ARRAYSIZE =
    ConnectionResponse_ResponseCode_ResponseCode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ResponseCode_descriptor() {
    return ConnectionResponse_ResponseCode_descriptor();
  }
  static inline const ::std::string& ResponseCode_Name(ResponseCode value) {
    return ConnectionResponse_ResponseCode_Name(value);
  }
  static inline bool ResponseCode_Parse(const ::std::string& name,
      ResponseCode* value) {
    return ConnectionResponse_ResponseCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .BasicProtobuf.ConnectionResponse.ResponseCode responseCode = 1;
  inline bool has_responsecode() const;
  inline void clear_responsecode();
  static const int kResponseCodeFieldNumber = 1;
  inline ::BasicProtobuf::ConnectionResponse_ResponseCode responsecode() const;
  inline void set_responsecode(::BasicProtobuf::ConnectionResponse_ResponseCode value);

  // required string sessionId = 2;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 2;
  inline const ::std::string& sessionid() const;
  inline void set_sessionid(const ::std::string& value);
  inline void set_sessionid(const char* value);
  inline void set_sessionid(const char* value, size_t size);
  inline ::std::string* mutable_sessionid();
  inline ::std::string* release_sessionid();
  inline void set_allocated_sessionid(::std::string* sessionid);

  // optional string message = 3;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 3;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:BasicProtobuf.ConnectionResponse)
 private:
  inline void set_has_responsecode();
  inline void clear_has_responsecode();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();
  inline void set_has_message();
  inline void clear_has_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* sessionid_;
  ::std::string* message_;
  int responsecode_;
  friend void  protobuf_AddDesc_basic_2eproto();
  friend void protobuf_AssignDesc_basic_2eproto();
  friend void protobuf_ShutdownFile_basic_2eproto();

  void InitAsDefaultInstance();
  static ConnectionResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// ConnectionResponse

// required .BasicProtobuf.ConnectionResponse.ResponseCode responseCode = 1;
inline bool ConnectionResponse::has_responsecode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConnectionResponse::set_has_responsecode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConnectionResponse::clear_has_responsecode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConnectionResponse::clear_responsecode() {
  responsecode_ = 200;
  clear_has_responsecode();
}
inline ::BasicProtobuf::ConnectionResponse_ResponseCode ConnectionResponse::responsecode() const {
  // @@protoc_insertion_point(field_get:BasicProtobuf.ConnectionResponse.responseCode)
  return static_cast< ::BasicProtobuf::ConnectionResponse_ResponseCode >(responsecode_);
}
inline void ConnectionResponse::set_responsecode(::BasicProtobuf::ConnectionResponse_ResponseCode value) {
  assert(::BasicProtobuf::ConnectionResponse_ResponseCode_IsValid(value));
  set_has_responsecode();
  responsecode_ = value;
  // @@protoc_insertion_point(field_set:BasicProtobuf.ConnectionResponse.responseCode)
}

// required string sessionId = 2;
inline bool ConnectionResponse::has_sessionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConnectionResponse::set_has_sessionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConnectionResponse::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConnectionResponse::clear_sessionid() {
  if (sessionid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sessionid_->clear();
  }
  clear_has_sessionid();
}
inline const ::std::string& ConnectionResponse::sessionid() const {
  // @@protoc_insertion_point(field_get:BasicProtobuf.ConnectionResponse.sessionId)
  return *sessionid_;
}
inline void ConnectionResponse::set_sessionid(const ::std::string& value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
  // @@protoc_insertion_point(field_set:BasicProtobuf.ConnectionResponse.sessionId)
}
inline void ConnectionResponse::set_sessionid(const char* value) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(value);
  // @@protoc_insertion_point(field_set_char:BasicProtobuf.ConnectionResponse.sessionId)
}
inline void ConnectionResponse::set_sessionid(const char* value, size_t size) {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sessionid_ = new ::std::string;
  }
  sessionid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BasicProtobuf.ConnectionResponse.sessionId)
}
inline ::std::string* ConnectionResponse::mutable_sessionid() {
  set_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    sessionid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:BasicProtobuf.ConnectionResponse.sessionId)
  return sessionid_;
}
inline ::std::string* ConnectionResponse::release_sessionid() {
  clear_has_sessionid();
  if (sessionid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = sessionid_;
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ConnectionResponse::set_allocated_sessionid(::std::string* sessionid) {
  if (sessionid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete sessionid_;
  }
  if (sessionid) {
    set_has_sessionid();
    sessionid_ = sessionid;
  } else {
    clear_has_sessionid();
    sessionid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:BasicProtobuf.ConnectionResponse.sessionId)
}

// optional string message = 3;
inline bool ConnectionResponse::has_message() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConnectionResponse::set_has_message() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConnectionResponse::clear_has_message() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConnectionResponse::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& ConnectionResponse::message() const {
  // @@protoc_insertion_point(field_get:BasicProtobuf.ConnectionResponse.message)
  return *message_;
}
inline void ConnectionResponse::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:BasicProtobuf.ConnectionResponse.message)
}
inline void ConnectionResponse::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:BasicProtobuf.ConnectionResponse.message)
}
inline void ConnectionResponse::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:BasicProtobuf.ConnectionResponse.message)
}
inline ::std::string* ConnectionResponse::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:BasicProtobuf.ConnectionResponse.message)
  return message_;
}
inline ::std::string* ConnectionResponse::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ConnectionResponse::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:BasicProtobuf.ConnectionResponse.message)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace BasicProtobuf

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::BasicProtobuf::ConnectionResponse_ResponseCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::BasicProtobuf::ConnectionResponse_ResponseCode>() {
  return ::BasicProtobuf::ConnectionResponse_ResponseCode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_basic_2eproto__INCLUDED
